"""Initial migration

Revision ID: d1277a61252f
Revises: 
Create Date: 2024-12-10 21:59:23.832057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1277a61252f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_completed', sa.DateTime(), nullable=True))

    with op.batch_alter_table('exercise_done', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_done', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('last_completed')

    # ### end Alembic commands ###
